# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    redirect_register_user.registration.completed:
        class: SMARTASK\ListnerBundle\Controller\DefaultController
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
